apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oracle.fullname" . }}
  labels: {{- include "oracle.labels" . | nindent 4 }}
type: Opaque
stringData:
  ORACLE_PWD: {{ .Values.oracle.sysPassword | quote }}        # official image
  ORACLE_PASSWORD: {{ .Values.oracle.sysPassword | quote }}   # gvenzl image
  APP_USER: {{ .Values.oracle.appUser | quote }}
  APP_USER_PASSWORD: {{ .Values.oracle.appPassword | quote }}
