apiVersion: v1
kind: Service
metadata:
  name: {{ include "oracle.fullname" . }}
  labels: {{- include "oracle.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: oracle
      port: {{ .Values.service.port }}
      targetPort: 1521
  selector: {{- include "oracle.selectorLabels" . | nindent 4 }}
