apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ibm-mq.fullname" . }}
  labels: {{- include "ibm-mq.labels" . | nindent 4 }}
type: Opaque
stringData:
  MQ_APP_PASSWORD: {{ .Values.mq.appPassword | quote }}
  MQ_ADMIN_PASSWORD: {{ .Values.mq.adminPassword | quote }}
