apiVersion: v1
kind: Service
metadata:
  name: {{ include "ibm-mq.fullname" . }}
  labels: {{- include "ibm-mq.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: qm
      port: {{ .Values.service.qmPort }}
      targetPort: 1414
    - name: web
      port: {{ .Values.service.webPort }}
      targetPort: 9443
  selector: {{- include "ibm-mq.selectorLabels" . | nindent 4 }}
