apiVersion: v1
kind: Secret
metadata:
  name: {{ include "artifactory.fullname" . }}
  labels: {{- include "artifactory.labels" . | nindent 4 }}
type: Opaque
stringData:
  ADMIN_USER: {{ .Values.admin.username | quote }}
  ADMIN_PASSWORD: {{ .Values.admin.password | quote }}
  # Access bootstrap creds file format: username=password
  bootstrap.creds: "{{ .Values.admin.username }}={{ .Values.admin.password }}"
  # Artifactory encryption master key + cluster join key (raw hex, no newline)
  master.key: "{{ .Values.masterKey }}"
  join.key: "{{ .Values.joinKey }}"
