apiVersion: v1
kind: Service
metadata:
  name: {{ include "artifactory.fullname" . }}
  labels: {{- include "artifactory.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: web
      port: {{ .Values.service.webPort }}
      targetPort: web
    - name: artifactory
      port: {{ .Values.service.artifactoryPort }}
      targetPort: artifactory
  selector: {{- include "artifactory.selectorLabels" . | nindent 4 }}
