{{- if or (not .Values.oracle.existingSecret) (not .Values.mq.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "debug-demo-app.fullname" . }}-secrets
  labels: {{- include "debug-demo-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if not .Values.oracle.existingSecret }}
  ORACLE_PASSWORD: {{ .Values.oracle.password | quote }}
  {{- end }}
  {{- if not .Values.mq.existingSecret }}
  MQ_PASSWORD: {{ .Values.mq.password | quote }}
  {{- end }}
  {{- if not .Values.valkey.existingSecret }}
  VALKEY_PASSWORD: {{ .Values.valkey.password | quote }}
  {{- end }}
{{- end }}
