#!/usr/bin/env bash
#
# install-haproxy-vm.sh — provision the second Lima VM running HAProxy as the
# external F5 stand-in. Idempotent: re-running is safe and fast.
#
# The VM plays the F5 role for BOTH traffic types:
#   - HTTP (L7, Pattern D): frontend :80 → RD node :80 (hostNetwork ingress)
#   - Valkey (L4, two-layer): TCP frontends 6379-6384 + 16379-16384 → the
#     Valkey shared MetalLB IP, same ports. The Valkey pods announce THIS
#     VM's IP (loadBalancer.announceIP), so MOVED redirects name the VIP —
#     exactly the production F5-without-CIS shape.
#
# Steps:
#   1. limactl start the VM (or skip if already running)
#   2. discover the Rancher Desktop node IP (the k8s node where
#      ingress-nginx hostNetwork is bound)
#   3. generate haproxy.cfg: HTTP backend <node-ip>:80 + Valkey TCP passthrough
#   4. push the config into the VM and reload haproxy
#   5. print the HAProxy VM's IP — this is the "F5 VIP" for the POC
#
# Output: the HAProxy VM IP is written to ./dumps/haproxy-vm-ip so
# scripts/install-stack.sh can pick it up for the /etc/hosts entry.
#
# Usage:
#   ./install-haproxy-vm.sh                  # provision (idempotent)
#   ./install-haproxy-vm.sh --status         # print state, do nothing
#   ./install-haproxy-vm.sh --remove         # stop+delete VM

set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
source "$SCRIPT_DIR/lib/common.sh"

VM_NAME="debug-demo-haproxy"
LIMA_YAML="$SCRIPT_DIR/lima-haproxy.yaml"
IP_OUT_FILE="$SCRIPT_DIR/../dumps/haproxy-vm-ip"

# Valkey L4 passthrough targets. Must match charts/valkey/values.yaml:
# loadBalancer.sharedIP and basePorts (client base 6379, bus base 16379,
# 6 nodes → +0..+5). Overridable for non-default chart values.
: "${VALKEY_LB_IP:=192.168.64.51}"
: "${VALKEY_CLIENT_BASE:=6379}"
: "${VALKEY_BUS_BASE:=16379}"
: "${VALKEY_NODE_COUNT:=6}"

MODE="install"
for a in "$@"; do
    case "$a" in
        --status) MODE="status" ;;
        --remove) MODE="remove" ;;
        -h|--help) sed -n '2,/^$/p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
        *) err "unknown arg: $a"; exit 64 ;;
    esac
done

require_cmd limactl

vm_status() {
    # Capture into a variable first — piping straight into python with
    # `set -o pipefail` on causes limactl to be SIGPIPE'd when python
    # calls sys.exit(0) mid-stream, which propagates as pipe exit 141.
    local out
    out="$(limactl list --format=json 2>/dev/null || true)"
    printf '%s\n' "$out" | python3 -c "
import json,sys
for line in sys.stdin:
    line = line.strip()
    if not line: continue
    try: v = json.loads(line)
    except: continue
    if v.get('name') == '$VM_NAME':
        print(v.get('status', 'Unknown'))
        sys.exit(0)
print('Missing')
"
}

vm_ip() {
    # Lima VM's shared-network IP (192.168.105.x). Asks the VM to inspect
    # its own interfaces because the limactl-side info doesn't expose this
    # consistently across versions.
    limactl shell "$VM_NAME" -- ip -4 addr show 2>/dev/null \
        | awk '/inet 192\.168\.105\./ { sub("/.*","",$2); print $2; exit }'
}

rd_node_ip() {
    # Rancher Desktop's k8s node has *two* IPs:
    #   ExternalIP = 192.168.64.2 (bridge100, vz-NAT — RD's dedicated subnet)
    #   InternalIP = e.g. 192.168.5.15 (on the Mac's en0 — the user's actual LAN)
    # hostNetwork pods bind 0.0.0.0:80 so they answer on BOTH. We prefer the
    # ExternalIP to keep ingress traffic on RD's dedicated subnet (not leaked
    # onto the user's WiFi/LAN). Falls back to InternalIP if ExternalIP is empty.
    require_cmd kubectl
    local ext int
    ext="$(kubectl get nodes -o jsonpath='{.items[0].status.addresses[?(@.type=="ExternalIP")].address}')"
    int="$(kubectl get nodes -o jsonpath='{.items[0].status.addresses[?(@.type=="InternalIP")].address}')"
    if [[ -n "$ext" ]]; then echo "$ext"; else echo "$int"; fi
}

generate_haproxy_cfg() {
    local node_ip="$1"
    cat <<EOF
# Auto-generated by scripts/install-haproxy-vm.sh — do not edit by hand.
# Models an external F5 VIP fronting hostNetwork ingress-nginx on
# Rancher Desktop. Backend = the RD k8s node IP on :80, where
# ingress-nginx-controller pod (hostNetwork=true) is listening.

global
    daemon
    maxconn 4096
    log stdout local0 info

defaults
    mode http
    log global
    option httplog
    option dontlognull
    option forwardfor
    option http-server-close
    timeout connect 5s
    timeout client  60s
    timeout server  60s
    timeout http-request 10s

# ----- Stats UI (optional, for poking at the LB itself) ---------------------
frontend stats
    bind *:8404
    stats enable
    stats uri /
    stats refresh 5s
    stats admin if TRUE

# ----- HTTP frontend: this is the "F5 VIP" --------------------------------
frontend http_front
    bind *:80
    # Preserve client IP so the app sees real source addresses (X-Forwarded-For).
    # Pattern D = no kube-proxy hop, so source IP is naturally preserved here too,
    # but adding the header is good practice for an L7-aware backend.
    default_backend ingress_nginx

# ----- Backend: the RD k8s node on :80 (ingress-nginx hostNetwork) ---------
backend ingress_nginx
    option httpchk GET /healthz
    http-check expect status 200
    # Single-node dev cluster; in production this would be 'server node-N <ip>:80'
    # repeated for every k8s node in the pool.
    server rd-node $node_ip:80 check inter 5s fall 3 rise 2

# ----- Valkey L4 passthrough: the "F5 VIP without CIS" shape ----------------
# One TCP listener per Valkey node, port-separated (client 6379-6384, bus
# 16379-16384), forwarding 1:1 to the same port on the in-cluster MetalLB
# shared IP. Plain L4 — no inspection; the Valkey wire protocol is stateful
# TCP. The pods announce THIS VM's IP (chart value loadBalancer.announceIP),
# so MOVED redirects sent to external clients name these listeners.
#
# The BUS ports matter even though external clients never dial them: Valkey
# nodes gossip with each other via the ANNOUNCED addresses, and kube-proxy
# doesn't know this VM's IP — so node-to-node gossip hairpins out through
# these listeners and back. Removing them collapses the cluster to
# cluster_state:fail.
EOF
    local i cport bport
    for i in $(seq 0 $((VALKEY_NODE_COUNT - 1))); do
        cport=$((VALKEY_CLIENT_BASE + i))
        bport=$((VALKEY_BUS_BASE + i))
        cat <<EOF

listen valkey_client_${cport}
    mode tcp
    option tcplog
    bind *:${cport}
    timeout client  600s
    timeout server  600s
    server valkey ${VALKEY_LB_IP}:${cport} check inter 5s fall 3 rise 2

listen valkey_bus_${bport}
    mode tcp
    option tcplog
    bind *:${bport}
    timeout client  600s
    timeout server  600s
    server valkey ${VALKEY_LB_IP}:${bport} check inter 5s fall 3 rise 2
EOF
    done
}

case "$MODE" in
    status)
        st="$(vm_status)"
        ip="$(vm_ip 2>/dev/null || echo '(VM not running)')"
        node="$(rd_node_ip 2>/dev/null || echo '(kubectl unavailable)')"
        echo "VM:           $VM_NAME"
        echo "Status:       $st"
        echo "VM IP:        $ip"
        echo "Backend node: $node"
        echo "Cached IP:    $(cat "$IP_OUT_FILE" 2>/dev/null || echo '(none)')"
        exit 0
        ;;
    remove)
        st="$(vm_status)"
        if [[ "$st" == "Missing" ]]; then
            info "$VM_NAME: not present, nothing to remove"
            rm -f "$IP_OUT_FILE"
            exit 0
        fi
        info "stopping $VM_NAME..."
        limactl stop "$VM_NAME" 2>&1 | sed 's/^/    /' || true
        info "deleting $VM_NAME..."
        limactl delete "$VM_NAME" 2>&1 | sed 's/^/    /' || true
        rm -f "$IP_OUT_FILE"
        info "removed"
        exit 0
        ;;
esac

# -------------------------------- install mode ----------------------------
mkdir -p "$(dirname "$IP_OUT_FILE")"

st="$(vm_status)"
case "$st" in
    Running)
        info "VM $VM_NAME already running"
        ;;
    Stopped)
        info "VM $VM_NAME exists, starting..."
        limactl start "$VM_NAME" 2>&1 | tail -3 | sed 's/^/    /'
        ;;
    Missing)
        info "creating VM $VM_NAME from $LIMA_YAML..."
        info "  (first boot pulls Alpine image + installs haproxy — ~2-3 min)"
        limactl start --tty=false --name="$VM_NAME" "$LIMA_YAML" 2>&1 \
            | tail -15 | sed 's/^/    /'
        ;;
    *)
        err "unexpected VM status: $st"
        exit 1
        ;;
esac

# Wait for VM to be reachable
for i in $(seq 1 20); do
    if limactl shell "$VM_NAME" -- true 2>/dev/null; then break; fi
    sleep 1
done
limactl shell "$VM_NAME" -- true 2>/dev/null || { err "VM not reachable via limactl shell"; exit 1; }

NODE_IP="$(rd_node_ip)"
if [[ -z "$NODE_IP" ]]; then
    err "could not discover RD k8s node IP (is kubectl pointed at rancher-desktop?)"
    exit 1
fi
info "RD k8s node IP (HAProxy backend): $NODE_IP"

# Generate config + push it into the VM
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT
generate_haproxy_cfg "$NODE_IP" > "$TMP"

# limactl cp puts files at /tmp by default; move into place with sudo
limactl cp "$TMP" "$VM_NAME:/tmp/haproxy.cfg.new" 2>&1 | sed 's/^/    /'
limactl shell "$VM_NAME" -- sudo sh -c '
    cp /tmp/haproxy.cfg.new /etc/haproxy/haproxy.cfg
    rm -f /tmp/haproxy.cfg.new
    # Validate before reload
    haproxy -c -f /etc/haproxy/haproxy.cfg
    rc-service haproxy reload || rc-service haproxy restart
' 2>&1 | sed 's/^/    /'

VM_IP="$(vm_ip)"
if [[ -z "$VM_IP" ]]; then
    err "could not determine VM IP on 192.168.105.0/24 — check Lima network config"
    exit 1
fi
echo "$VM_IP" > "$IP_OUT_FILE"

# Smoke test: HAProxy reachable from Mac, forwards to RD node
info "verifying end-to-end..."
if curl -fsS -m 5 -o /dev/null "http://$VM_IP/healthz" 2>/dev/null; then
    info "  HAProxy VM → ingress-nginx /healthz: OK"
else
    info "  HAProxy VM → ingress-nginx /healthz: no response (ingress-nginx may not be up yet)"
fi

echo
info "HAProxy VM IP: $VM_IP   (cached at $IP_OUT_FILE)"
info "Backend:       $NODE_IP:80 (Rancher Desktop k8s node)"
info "Stats:         http://$VM_IP:8404/"
info ""
info "Add to /etc/hosts (install-stack.sh does this automatically):"
info "  $VM_IP debug-demo.local"
